Добавлен скелет header and modal
ProjectTeam18/parcel-project-template pull request #11
Opened 2020-09-16 16:27 UTC by AllaSelezneva

Попытка №1)) Закинула скелет без стилей, на пробу

2020-09-16 19:29 UTC, KotenkoNata requested changes

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/header.html
> +      <a href="./index.html" class="logo"
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/header.html
> +    <button type="button" class="btn-consult">Консультация по телефону</button>
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/header.html
> +        class="icon-menu"
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/header.html
> +      class="btn-burger"
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/header.html
> +        <use class="icon-menu" xlink:href="./images/sprite.svg#menu"></use>
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/modal.html
> +      class="btn-burger icon-cross"
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/partials/modal.html
> +    <button type="button" class="btn-consult-modal">
Название класса должно начинаться с названии секции

2020-09-16 19:29 UTC, KotenkoNata commented on src/sass/main.css
> +@charset "UTF-8";
Мы работаем напрямую только с `sass` (`scss`) фалами. `css` фалы нам генерирует сборщик. Поэтому мы не добавляем `css` фалы в `git` (`Github`). Его нужно удалить

2020-09-16 19:29 UTC, KotenkoNata commented on src/sass/main.css.map
> +{
Мы работаем напрямую только с `sass` (`scss`) фалами. `css` фалы нам генерирует сборщик. Поэтому мы не добавляем `css` фалы в `git` (`Github`). Его нужно удалить

2020-09-17 20:05 UTC, KotenkoNata requested changes
пред тем как делать `push` на `GitHub` со своими изменениями, протестируй локально на своем компьютере с помощью `npm run dev`. Проект должен собраться без ошибок, ни в терминале, ни на сайте.

2020-09-17 20:05 UTC, KotenkoNata commented on src/partials/modal.html
> +          <use class="header-icon-cross" xlink:href="../images/sprite.svg#cross"></use>
Нужно заменить 2 точки на 1, как сделано на примере снизу:

```suggestion
          <use class="header-icon-cross" xlink:href="./images/sprite.svg#cross"></use>
```

2020-09-17 20:05 UTC, KotenkoNata commented on src/partials/modal.html
> +          src="../images/logo-modal.png"
Нужно заменить 2 точки на 1, как сделано на примере снизу:

```suggestion
          src="./images/logo-modal.png"
```

2020-09-17 20:05 UTC, KotenkoNata commented on src/partials/header.html
> +          src="../images/logo.png"
Нужно заменить 2 точки на 1, как сделано на примере снизу:

```suggestion
          src="./images/logo.png"
```

2020-09-17 20:05 UTC, KotenkoNata commented on src/partials/header.html
> +            <use class="header-icon-menu" xlink:href="../images/sprite.svg#menu"></use>
Нужно заменить 2 точки на 1, как сделано на примере снизу:

```suggestion
            <use class="header-icon-menu" xlink:href="./images/sprite.svg#menu"></use>
```

2020-09-17 20:20 UTC, AllaSelezneva commented on src/partials/modal.html
> +          <use class="header-icon-cross" xlink:href="../images/sprite.svg#cross"></use>
в том то и дело, что я не могла проверить это локально, выдавало ошибку. ментор сказал запушить, чтобы он посмотрел на ошибки. В итоге сказал эту ветку не трогать и создать новую, а эту потом удалим. Я создала, сделала всё то же самое, конфликт в итоге выдавали те две точки!! в этот раз я их не ставила и все пошло как надо. Запушила вторую ветку, 
пысы: не могу написать тебе в слак, нам написано, что сейчас мои сообщения не дойдут, так как ты в режиме  - не беспокоить

2020-09-18 06:56 UTC, KotenkoNata commented
PR закрываю, ветка не актуальна

//cc @AllaSelezneva

2020-09-18 06:56 UTC, closed without merging