Hero
ProjectTeam18/parcel-project-template pull request #14
Opened 2020-09-16 18:38 UTC by RomanDolid

2020-09-16 19:16 UTC, KotenkoNata requested changes

2020-09-16 19:16 UTC, KotenkoNata commented on src/index.html
> +      <include src="./partials/hero.html"></include>
Перемести эту секцию как первую в main блоке

2020-09-16 19:41 UTC, RomanDolid commented
посмотри пж, все верно сделал?

2020-09-16 19:46 UTC, KotenkoNata requested changes

2020-09-16 19:46 UTC, KotenkoNata commented on src/index.html
> +      <include src="./partials/hero.html"></include>
Не нужно удалять подключение секции Главные проблемы. Перед Главными проблемами добавь свою

2020-09-16 19:59 UTC, RomanDolid commented
не понимаю, что не так :(

2020-09-16 20:07 UTC, KotenkoNata commented
<img width="1881" alt="Screenshot 2020-09-16 at 23 01 09" src="https://user-images.githubusercontent.com/35960689/93387128-694f0280-f871-11ea-92af-2fd1d978c530.png">

2020-09-16 20:40 UTC, RomanDolid commented
вернул назад то, что удалил

2020-09-17 07:45 UTC, KotenkoNata approved these changes

2020-09-17 07:45 UTC, merged